### ISSUE TITLE
ld-linux-x86-64.so missing

### ISSUE THREAD

**Issue by Motik68** [bartbutenaers/node-red-contrib-v8-cpu-profiler#2]
Hello,

When I install node-red-contrib-v8-cpu-profiler in Node Red v3.0.2 I get an error message: `ERR_DLOPEN_FAILED`.

In the logs I have:
`[info]  - node-red-contrib-v8-cpu-profiler:v8-cpu-profiler : Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /config/node-red/node_modules/v8-profiler-next/build/binding/Release/node-v93-linux-x64/profiler.node)`

Any idea?

**Comment by bartbutenaers** [comment]
@Motik68,
Somebody else already reported this issue [here](https://discourse.nodered.org/t/announce-node-red-contrib-v8-cpu-profiler-beta/56017/14?u=bartbutenaers).  I have no idea why it happens for some users.  Unfortunately he has not reported this as an issue in the [v8-profiler-next](https://github.com/hyj1991/v8-profiler-next) repository (which I use for this Node-RED node), so the problem is not solved yet...
Bart

**Comment by Motik68** [comment]
Thank you for your answer @bartbutenaers. I solved the issue by adding gcompat, which contains ld-linux-x86-64.so, to my system. Don't know why it was missing in the first place, but I am using Node Red as a ready-made docker container inside Home Assistant, so I guess it was omitted there.

**Comment by bartbutenaers** [comment]
Hi @Motik68,
Thanks for sharing your solution!!

**Comment by ouinouin** [comment]
@bartbutenaers , i have the exact same issue, the problem lies on the integration of baremetal or very small images created under docker which doesnt embed this library. it sound logical that under home assistant you have those issues since home assistan addons relies on docker images.

here is the libs i could find on the official nodered docker image : 
```
bash-5.1$ ls /lib/
apk/                   libapk.so.3.12.0       libc.musl-x86_64.so.1  libkmod.so.2.3.7       libudev.so.1.6.3       mdev/                  udev/                  
firmware/              libblkid.so.1          libcrypto.so.1.1       libssl.so.1.1          libz.so.1              modules-load.d/        
ld-musl-x86_64.so.1    libblkid.so.1.1.0      libkmod.so.2           libudev.so.1           libz.so.1.2.12         sysctl.d/              
bash-5.1$ ls /usr/lib
Scrt1.o                   libbrotlidec.so.1         libctf-nobfd.so.0         libgcc_s.so               libitm.so                 libmpdec.so.3             libpsx.so.2.64            libstdc++.so.6.0.29
bash                      libbrotlidec.so.1.0.9     libctf-nobfd.so.0.0.0     libgcc_s.so.1             libitm.so.1               libmpfr.so.6              libpthread.a              libstdc++fs.a
bfd-plugins               libbrotlienc.so.1         libctf.so.0               libgdbm.so.6              libitm.so.1.0.0           libmpfr.so.6.1.0          libpython3.10.so.1.0      libsupc++.a
crt1.o                    libbrotlienc.so.1.0.9     libctf.so.0.0.0           libgdbm.so.6.0.0          liblzma.so.5              libncursesw.so.6          libpython3.so             libudev.so.1
crti.o                    libbz2.so.1               libcurl.so.4              libgdbm_compat.so.4       liblzma.so.5.2.5          libncursesw.so.6.3        libreadline.so.8          libudev.so.1.6.3
crtn.o                    libbz2.so.1.0.8           libcurl.so.4.8.0          libgdbm_compat.so.4.0.0   libm.a                    libnghttp2.so.14          libreadline.so.8.1        libutil.a
engines-1.1               libc.a                    libdl.a                   libgmp.so.10              libmagic.so.1             libnghttp2.so.14.21.2     libresolv.a               libxnet.a
gcc                       libc.so                   libedit.so.0              libgmp.so.10.4.1          libmagic.so.1.0.0         libopcodes-2.38.so        librt.a                   libzstd.so.1
libatomic.a               libcap.so.2               libedit.so.0.0.68         libgomp.a                 libmenuw.so.6             libpanelw.so.6            libsqlite3.so.0           libzstd.so.1.5.2
libatomic.so              libcap.so.2.64            libexpat.so.1             libgomp.so                libmenuw.so.6.3           libpanelw.so.6.3          libsqlite3.so.0.8.6       modules-load.d
libatomic.so.1            libcc1.so                 libexpat.so.1.8.8         libgomp.so.1              libmpc.so.3               libpcre2-8.so.0           libssl.so.1.1             python3.10
libatomic.so.1.2.0        libcc1.so.0               libffi.so.8               libgomp.so.1.0.0          libmpc.so.3.2.1           libpcre2-8.so.0.11.0      libssp_nonshared.a        rcrt1.o
libbfd-2.38.so            libcc1.so.0.0.0           libffi.so.8.1.0           libisl.so.22              libmpdec++.so.2.5.1       libpcre2-posix.so.3       libstdc++.a               ssh
libbrotlicommon.so.1      libcrypt.a                libformw.so.6             libisl.so.22.0.0          libmpdec++.so.3           libpcre2-posix.so.3.0.2   libstdc++.so
libbrotlicommon.so.1.0.9  libcrypto.so.1.1          libformw.so.6.3           libitm.a                  libmpdec.so.2.5.1         libpsx.so.2               libstdc++.so.6
```
if you re interrested to report to the nodered maintainers, for them to include the lib in next images, problem might be the portability.

**Comment by bartbutenaers** [comment]
Hi @ouinouin,
Unfortunately my private live at the moment doesn't allow me to digg into detail in this kind of issues.
If you know the solution, please be my guest to report it with the Node-RED core team.
If I am not mistaken you need to do it in [this](https://github.com/node-red/node-red-docker) repository.
And if you do, please add a link to your ticket here so others can do a follow up.
Thanks!!
Bart

**Comment by Impact123** [comment]
I worked around this by adding this to my `compose.yaml`
```yaml
entrypoint: "/bin/bash -c 'apk add gcompat && bash entrypoint.sh'"
```
Maybe worth documenting?

**Comment by ouinouin** [comment]
> I worked around this by adding this to my `compose.yaml`
> 
> ```yaml
> entrypoint: "/bin/bash -c 'apk add gcompat && bash entrypoint.sh'"
> ```
> 
> Maybe worth documenting?

actually i m taking a bit of time to try this, but i get the following resulta while doing docker-compose up : 
`Attaching to nodered
nodered  | ERROR: Unable to lock database: Permission denied
nodered  | ERROR: Failed to open apk database: Permission denied
nodered exited with code 99
`
@Impact123 do you have a custom docker nodered image  or something ?

edit : i see that you need to have to declare user as root somewhere in the compose.yml. can you post your compose file to make it reproductible ?

**Comment by Impact123** [comment]
I don't use this any more but I just have
```yaml
image: nodered/node-red
```
you might have to use
```yaml
user: root
```
whether you want to do that is your choice, of course.
~~You might also be able to only temporarily switch to root just to run `apk` (`su -c ... && bash entrypoint.sh`) but you have to test that yourself.~~

**Comment by Impact123** [comment]
@ouinouin I was too curious and tested this. It turns out you can't switch to `root` from a normal user which makes sense.
But you can do this
```yaml
user: root
entrypoint: "/bin/bash -c 'apk add gcompat && su -c ./entrypoint.sh node-red'"
```
The container is started as `root` but node-red itself is started as `node-red`.
It's shown as `impact` because my user's UID is `1000` as well but `su` doesn't seem to accept it as an argument.
```
$ docker compose top node-red
node-red
UID      PID    PPID   C    STIME   TTY   TIME       CMD
impact   2625   2604   0    11:25   ?     00:00:00   /bin/bash ./entrypoint.sh
impact   2638   2625   0    11:25   ?     00:00:00   node-red
```
```
$ docker compose exec node-red grep node-red /etc/passwd
node-red:x:1000:1000:Linux User,,,:/usr/src/node-red:/bin/ash
```
```
$ id
uid=1000(impact) gid=1000(impact) groups=1000(impact),...
```
Not sure what implications this has but it seems to work. Does that help?

**Comment by ouinouin** [comment]
@Impact123 nice test, it will be helpful for many docker users.
i could start the profiling, unfortunately all the consumed time i was seeking for is located in internal functions of nodered :-D
